### ISSUE TITLE
当driver配置为s3或者阿里的oss的时候，list有错

### ISSUE THREAD

**Issue by superwen** [laravel-admin-extensions/media-manager#1]
![default](https://user-images.githubusercontent.com/364819/30112317-8111855a-9343-11e7-80fe-2793698a8d8b.png)
但是却可以上传文件和新建文件夹。
![default](https://user-images.githubusercontent.com/364819/30112404-dd8c004e-9343-11e7-8609-ba985db8e772.png)
主要应该是判断文件夹是否存在，对于云存储来说有点问题。

**Comment by z-song** [comment]
readme第一句就写了只能work for local storage

因为各个oss平台对了于laravel的filesystem接口并没有完全实现，所以只有在local storage才能实现所有的文件操作。

**Comment by sandersyao** [comment]
作为折中方案 如果使用阿里云的oss可以使用ossfs加载bucket为磁盘镜像 之后就可以使用local storage了。但问题也会随之而来，随着目录下文件数量的增加遍历整个目录就相当于使用前缀查询下面所有匹配到的对象，响应速度超级慢。

还是希望以后能有个兼容OSS或者COS的扩展，一旦兼容，不能分页导致页面效率低的问题也就迎刃而解了。
