### ISSUE TITLE
Can't delete a file

### ISSUE THREAD

**Issue by blackcolt** [laravel-admin-extensions/media-manager#16]
Hi, trying to delete a file (clicking on the trashcan on the side or on the record.
I don't see any network activity when clicking the delete button.

Config:

filesystems.php
``` 'disks' => [ 

 'public' => [
            'driver' => 'local',
            'root' => storage_path('app/'),
            'url' => env('APP_URL') . '/storage',    // set url
            'visibility' => 'public',
        ],
] 
```

admin.php
 ```
'extensions' => [
 
        'media-manager' => [
            'disk' => 'public'   // Points to the disk set in config/filesystem.php
        ],
    ]
```

Will appreciate any help or suggestion, 

Thanks a lot!

**Comment by z-song** [comment]
Fixed now, upgrade to `v1.0.2`, and don't forget to run `artisan view:clear` after upgrade
