### ISSUE TITLE
能否支持laravel6.0

### ISSUE THREAD

**Issue by huangxinkui** [laravel-admin-extensions/media-manager#24]
现在安装报错

**Comment by vonsogt** [comment]
@z-song please fix this repo soon
Thanks

**Comment by UsamaITS** [comment]
Laravel : ^6.2

Dependency resolution completed in 0.112 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework (locked at v6.2.0, required as ^6.2) -> satisfiable by laravel/framework[v6.2.0].
    - Conclusion: don't install laravel-admin-ext/media-manager v1.0.2
    - Conclusion: don't install laravel-admin-ext/media-manager v1.0.1
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.7].
    - Can only install one of: encore/laravel-admin[v1.7.7, 1.5.x-dev].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.7].
    - laravel-admin-ext/media-manager v1.0 requires encore/laravel-admin 1.5.* -> satisfiable by encore/laravel-admin[1.5.x-dev].
    - Installation request for laravel-admin-ext/media-manager ^1.0 -> satisfiable by laravel-admin-ext/media-manager[v1.0, v1.0.1, v1.0.2].
    - Installation request for encore/laravel-admin (locked at v1.7.7, required as ^1.7) -> satisfiable by encore/laravel-admin[v1.7.7].

Installation failed, reverting ./composer.json to its original content.

**Thanks in advance.**

**Comment by z-song** [comment]
@huangxinkui @vonsogt @UsamaITS Fixed
