### ISSUE TITLE
我的图片缩略图显示不了

### ISSUE THREAD

**Issue by EddyAnn** [laravel-admin-extensions/media-manager#3]
![image](https://user-images.githubusercontent.com/18549545/30472088-bd092ed2-9a2d-11e7-8da4-2989e40c4d24.png)
就是这个样子,要怎么解决呢

**Comment by z-song** [comment]
https://laravel.com/docs/5.5/filesystem#file-urls

在filesystem.php里，你设置的disk要加一项`url`设置，作为访问前缀
