### ISSUE TITLE
Error In MediaController.php line 21 :

### ISSUE THREAD

**Issue by gekomod** [laravel-admin-extensions/media-manager#31]
Error In MediaController.php line 21 :
  Call to undefined function Encore\Admin\Media\admin_assets_require()

**Comment by lovelypuspen** [comment]
first run this 
composer require encore/laravel-admin -vvv

now see versions : * v1.8.12,

// For laravel-admin 1.x
composer require laravel-admin-ext/media-manager:1.x -vvv

// For laravel-admin 2.x
composer require laravel-admin-ext/media-manager:2.x -vvv
-------------now clear previous files ----------------
/ / Force to publish release assets files
Php artisan vendor:publish --tag=laravel-admin-assets --force

// Force to publish release lang files
php artisan vendor:publish --tag=laravel-admin-lang --force

/ / Clean up the view cache
Php artisan view:clear
