### ISSUE TITLE
i can not download files (Files are opend as binary data)

### ISSUE THREAD

**Issue by SeiyaMakino** [laravel-admin-extensions/media-manager#7]
I uploaded some images, and it are seems good work.
But I can not download these files from lists on meida-manager .
So the issue is opened as binary data directly.

please tell me How do I download my files...

Im using laravel 5.5 

<img width="1191" alt="screenshot 2018-01-24 14 17 04" src="https://user-images.githubusercontent.com/9941826/35315759-731179ce-0111-11e8-813c-169d2a43eec9.png">
<img width="620" alt="screenshot 2018-01-24 14 19 42" src="https://user-images.githubusercontent.com/9941826/35315790-a7287488-0111-11e8-96a7-9fed5cfe1cd7.png">

**Comment by jxlwqq** [comment]
the same problem

**Comment by jxlwqq** [comment]
the problem is fixed, but the author is not merging yet. see #10

**Comment by z-song** [comment]
fixed
